# Generated by Django 4.1.1 on 2022-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vino', models.CharField(max_length=255, verbose_name='Виноградники')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('aspect', models.CharField(max_length=255, verbose_name='Экспозиция')),
                ('slope', models.CharField(max_length=255, verbose_name='Уклон')),
                ('water', models.CharField(max_length=255, verbose_name='Затопляемость')),
            ],
        ),
    ]
