# Generated by Django 4.1.1 on 2022-09-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinogradnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Vinogradnik', models.CharField(max_length=150)),
                ('number_Vinogradnik', models.IntegerField()),
                ('shirota_Vinogradnik', models.CharField(max_length=15)),
                ('dolgota_Vinogradnik', models.CharField(max_length=15)),
                ('description_Vinogradnik', models.CharField(max_length=350)),
                ('image_Vinogradnik', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vinograd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Vinograd', models.CharField(max_length=150)),
                ('description_Vinogradnik', models.CharField(max_length=350)),
                ('image_Vinogradnik', models.ImageField(upload_to='')),
                ('vinogradnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.vinogradnik')),
            ],
        ),
    ]
